name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'
    
    # Déplacer les fixtures avant l'installation de production
    - run: |
        mkdir -p ./backup
        mv ./src/DataFixtures ./backup/
    
    # Installation en mode production
    - run: composer install --no-dev --optimize-autoloader --no-scripts
    
    # Nettoyage du cache en production
    - run: |
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/DataFixtures/**
          backup/**